---
# This playbook deploys a simple standalone Tomcat + mysql

- hosts: tomcat
  roles:
    - tomcat
  vars:
    - mysql_ip: $mysql_softfire-internal
  user: ubuntu

- hosts: mysql
  roles:
    - mysql
  user: ubuntu
