---

- name: Add mariadb repo
  yum_repository:
    name: mariadb_repo
    description: mariadb_repo
    baseurl: http://yum.mariadb.org/10.1/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes


- name: Ensure MySQL packages are installed.
  yum:
    name: MariaDB-server
    state: present
  
- name: Ensure MySQL server is running and enabled
  service:
    name: mariadb
    state: started
    enabled: yes