---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: tomcat
  roles:
    - tomcat
  vars:
    - mysql_ip: $mysql_softfire-internal
    - http_port: 8080

- hosts: mysql
  roles:
    - mysql

